#!/usr/bin/env python3
"""Plan (and de-risk) the evidence-summary backfill for already-pushed deliverables.

Context: the human-readable evidence layer (dossier `summary` + top-level
`evidenceOverview`) is generated by the /exp-review synthesize step and rendered
by the Paraloom client. Deliverables pushed BEFORE that change have no summaries;
their Evidence tab still renders the raw dense docs. This tool inventories those
deliverables and tells you, per slug, whether a backfill would be a clean
summaries-only change or would also carry content drift.

It is READ-ONLY by default and never touches Paraloom: it works entirely from the
local experiment folders. `--check-prod` additionally GETs the public API to
confirm the live state (that request records a "viewed" activity — see the note it
prints).

The drift check is deterministic: it rebuilds the manifest from the current
`manifest-inputs.json` + article + dossier (via tools/build-deliverable-manifest.py)
to a temp file and diffs it against the on-disk `deliverable.json`, ignoring the
summary fields. If they match, adding summaries and re-pushing changes ONLY the
summary fields — a safe backfill. If they differ, the local source has drifted
since the last push and a re-push would carry those changes too.

    python3 tools/backfill-evidence-summaries.py            # inventory + plan
    python3 tools/backfill-evidence-summaries.py --check-prod   # also verify live state
    python3 tools/backfill-evidence-summaries.py --json         # machine-readable

Backfill procedure for each slug the plan marks READY (after the SaaS deploy):
  1. Generate summaries into experiments/<slug>/manifest-inputs.json:
       - dossierSummaries: { "<dossier filename>": "<plain-language summary>", ... }
       - evidenceOverview: "<featured why-we're-confident narrative>"
     following the spec in .claude/workflows/exp-review.js (item 8) /
     EXPERIMENT_WORKFLOW.md. Do NOT re-run the review battery for a backfill.
  2. python3 tools/build-deliverable-manifest.py --experiment-dir experiments/<slug>
  3. /exp-deliver {"slug":"<slug>","teamId":<team>}   # prod revision re-push,
     by-reference (keeps the ~90KB dossier intact); do NOT pass send:true.
Prereq: the by-reference staging endpoint must be live on prod and
PARALOOM_API_TOKEN set, or the push falls back to the inline path that drops the
dossier. See docs/evidence-summary-backfill.md.
"""
import argparse
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BUILDER = REPO / "tools" / "build-deliverable-manifest.py"

# Content sections whose drift means a re-push would change client-visible content
# (as opposed to benign status/publishPlan differences a fresh rebuild may derive).
CONTENT_SECTIONS = ("article", "opportunity", "checklist", "actionItems", "dossier")


def parse_experiment_md(text):
    """Best-effort pull of the prod token + recorded ids from experiment.md prose."""
    out = {"prod_token": None, "deliverable_id": None, "team_id": None}
    m = re.search(r"app\.paraloom\.ai/d/([A-Za-z0-9_-]{20,})", text)
    if m:
        out["prod_token"] = m.group(1)
    # Prod deliverable id only — must not pick up the "Local deliverable id N" lines.
    # Two recorded formats: "**Deliverable id (prod):** N" and "**Deliverable:** N (PROD".
    m = (re.search(r"\*\*Deliverable id \(prod\):\*\*\s*(\d+)", text)
         or re.search(r"\*\*Deliverable:\*\*\s*(\d+)\s*\(PROD", text, re.IGNORECASE))
    if m:
        out["deliverable_id"] = int(m.group(1))
    m = re.search(r"\*\*Team:\*\*\s*(\d+)", text)
    if not m:
        m = re.search(r"\bteam[_ ]?(?:id)?[:\s]+(\d+)\b", text, re.IGNORECASE)
    if m:
        out["team_id"] = int(m.group(1))
    return out


def has_summaries(manifest):
    if manifest.get("evidenceOverview"):
        return True
    return any(d.get("summary") for d in manifest.get("dossier", []))


def strip_summaries(manifest):
    m = json.loads(json.dumps(manifest))  # deep copy
    m.pop("evidenceOverview", None)
    for d in m.get("dossier", []):
        d.pop("summary", None)
    return m


def diff_sections(a, b):
    """Return the set of top-level/deliverable sections that differ (summaries ignored)."""
    a, b = strip_summaries(a), strip_summaries(b)
    differ = set()
    da, db = a.get("deliverable", {}), b.get("deliverable", {})
    if da.get("article", {}).get("markdown") != db.get("article", {}).get("markdown"):
        differ.add("article")
    for k in ("status", "title", "publishPlan"):
        if da.get(k) != db.get(k):
            differ.add(k)
    for k in ("opportunity", "checklist", "actionItems"):
        if a.get(k) != b.get(k):
            differ.add(k)
    # dossier: compare label+markdown pairs (order-sensitive, mirrors the builder)
    if [(d.get("label"), d.get("markdown")) for d in a.get("dossier", [])] != \
       [(d.get("label"), d.get("markdown")) for d in b.get("dossier", [])]:
        differ.add("dossier")
    return differ


def rebuild_drift(exp_dir):
    """Rebuild from current inputs to a temp file; diff vs the on-disk deliverable.json."""
    deliv = exp_dir / "deliverable.json"
    if not deliv.exists():
        return ("no-deliverable", None)
    if not (exp_dir / "manifest-inputs.json").exists():
        return ("no-inputs", None)
    existing = json.loads(deliv.read_text(encoding="utf-8"))
    with tempfile.NamedTemporaryFile("w+", suffix=".json", delete=True) as tmp:
        proc = subprocess.run(
            [sys.executable, str(BUILDER), "--experiment-dir", str(exp_dir), "--output", tmp.name],
            capture_output=True, text=True,
        )
        if proc.returncode != 0:
            return ("rebuild-failed", (proc.stderr or proc.stdout).strip().splitlines()[-1:] or ["unknown"])
        rebuilt = json.loads(Path(tmp.name).read_text(encoding="utf-8"))
    return ("ok", diff_sections(rebuilt, existing))


def check_prod(token, timeout=15):
    """GET the public API to confirm live state. Records a 'viewed' activity."""
    url = f"https://app.paraloom.ai/api/public/deliverables/{token}"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            data = json.loads(r.read().decode("utf-8"))
    except Exception as e:  # noqa: BLE001 - report any failure, don't crash the inventory
        return {"reachable": False, "error": str(e)}
    manifest = data.get("manifest") or {}
    article = (manifest.get("deliverable") or {}).get("article") or {}
    return {
        "reachable": True,
        "status": (data.get("deliverable") or {}).get("status"),
        "has_summaries": has_summaries(manifest),
        "dossier_count": len(manifest.get("dossier") or []),
        "article_md": article.get("markdown") or "",
    }


def classify(rec):
    if not rec["prod_token"]:
        return "SKIP", "not pushed to prod (no app.paraloom.ai token recorded)"
    if rec["local_has_summaries"]:
        return "DONE", "deliverable.json already carries summaries"
    state, detail = rec["rebuild_state"], rec["rebuild_detail"]
    if state == "no-inputs":
        return "REVIEW", "no manifest-inputs.json — cannot rebuild; generate inputs or patch the live manifest"
    if state == "rebuild-failed":
        return "REVIEW", f"rebuild failed: {detail}"
    content_drift = sorted(d for d in (detail or set()) if d in CONTENT_SECTIONS)
    if content_drift:
        return "REVIEW", f"local source drifted in: {', '.join(content_drift)} — a re-push would carry these too"
    benign = sorted(d for d in (detail or set()) if d not in CONTENT_SECTIONS)
    note = "clean — backfill is summaries-only" + (f" (benign diff: {', '.join(benign)})" if benign else "")
    return "READY", note


def main():
    ap = argparse.ArgumentParser(description="Plan the evidence-summary backfill (read-only).")
    ap.add_argument("--experiments-dir", default=str(REPO / "experiments"))
    ap.add_argument("--check-prod", action="store_true", help="also GET the public API per token (records a view)")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    args = ap.parse_args()

    exp_root = Path(args.experiments_dir)
    records = []
    for deliv in sorted(exp_root.glob("*/deliverable.json")):
        exp_dir = deliv.parent
        slug = exp_dir.name
        manifest = json.loads(deliv.read_text(encoding="utf-8"))
        md = exp_dir / "experiment.md"
        meta = parse_experiment_md(md.read_text(encoding="utf-8")) if md.exists() else {"prod_token": None, "deliverable_id": None, "team_id": None}
        state, detail = rebuild_drift(exp_dir)
        rec = {
            "slug": slug,
            "prod_token": meta["prod_token"],
            "deliverable_id": meta["deliverable_id"],
            "team_id": meta["team_id"],
            "local_has_summaries": has_summaries(manifest),
            "local_dossier_count": len(manifest.get("dossier", [])),
            "rebuild_state": state,
            "rebuild_detail": sorted(detail) if isinstance(detail, set) else detail,
        }
        if args.check_prod and meta["prod_token"]:
            prod = check_prod(meta["prod_token"])
            if prod.get("reachable"):
                prod["article_matches_local"] = (
                    prod.pop("article_md", "") == manifest.get("deliverable", {}).get("article", {}).get("markdown", "")
                )
            rec["prod"] = prod
        rec["plan"], rec["plan_note"] = classify(rec)
        records.append(rec)

    if args.json:
        print(json.dumps(records, indent=2))
        return

    print("Evidence-summary backfill inventory (read-only)\n")
    if args.check_prod:
        print("  note: --check-prod GETs each public deliverable, which records a 'viewed' activity.\n")
    width = max((len(r["slug"]) for r in records), default=4)
    print(f"  {'SLUG'.ljust(width)}  PROD  DELIV  SUMMARIES  PLAN     NOTE")
    for r in records:
        prod = "yes " if r["prod_token"] else "no  "
        deliv = str(r["deliverable_id"] or "-").ljust(5)
        summ = "yes      " if r["local_has_summaries"] else "missing  "
        line = f"  {r['slug'].ljust(width)}  {prod}  {deliv}  {summ}  {r['plan'].ljust(7)}  {r['plan_note']}"
        print(line)
        if r.get("prod"):
            p = r["prod"]
            if p.get("reachable"):
                print(f"  {' '.ljust(width)}        prod: status={p['status']} summaries={p['has_summaries']} "
                      f"dossier={p['dossier_count']} article_matches_local={p.get('article_matches_local')}")
            else:
                print(f"  {' '.ljust(width)}        prod: unreachable ({p.get('error')})")

    ready = [r for r in records if r["plan"] == "READY"]
    review = [r for r in records if r["plan"] == "REVIEW"]
    print()
    if ready:
        print(f"READY to backfill ({len(ready)}) — after the SaaS deploy, per slug:")
        for r in ready:
            team = r["team_id"] if r["team_id"] is not None else "<teamId>"
            print(f"  • {r['slug']}")
            print(f"      1. generate summaries → experiments/{r['slug']}/manifest-inputs.json "
                  f"(dossierSummaries + evidenceOverview; see docs/evidence-summary-backfill.md)")
            print(f"      2. python3 tools/build-deliverable-manifest.py --experiment-dir experiments/{r['slug']}")
            did = f" → revision push to prod deliverable id {r['deliverable_id']}" if r["deliverable_id"] else \
                  " ⚠ prod deliverable id not parsed — confirm it in experiment.md so this is a REVISION, not a new record"
            print(f"      3. /exp-deliver {{\"slug\":\"{r['slug']}\",\"teamId\":{team}}}   # no send;{did}")
    if review:
        print(f"\nNEEDS REVIEW ({len(review)}) — decide before backfilling:")
        for r in review:
            print(f"  • {r['slug']}: {r['plan_note']}")
    if not ready and not review:
        print("Nothing to backfill — every prod deliverable already carries summaries.")


if __name__ == "__main__":
    main()
